name: Unit

on: [push, pull_request]

env:
  GITHUB_ACTIONS: true

jobs:
  test:
    name: "Tests (${{ matrix.os }})"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with: { go-version-file: 'go.mod' }
      - run: go version
      - run: make test-unit race=true
        if: matrix.os != 'ubuntu-latest'
      - run: make test-unit race=true coverage=true
        if: matrix.os == 'ubuntu-latest'
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: tmp/unit.cov
          flags: unit
        if: matrix.os == 'ubuntu-latest'

  bench:
    name: Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with: { go-version-file: 'go.mod' }
      - run: go version
      - run: make test-bench
