name: Unit

on: [push, pull_request]

env:
  GITHUB_ACTIONS: true

jobs:
  test:
    name: "Tests (${{ matrix.os }})"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        go: ['1.x']
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with: { fetch-depth: 1 }
      - uses: actions/setup-go@v3
        with: { go-version: "${{ matrix.go }}" }
      - run: go version
      - run: make test-unit race=true
      - uses: codecov/codecov-action@v1
        with:
          file: tmp/unit.cov
          flags: unit
        if: matrix.os == 'ubuntu-latest'

  bench:
    name: Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: { fetch-depth: 1 }
      - uses: actions/setup-go@v3
        with: { go-version: '1.x' }
      - run: go version
      - run: make test-bench
